import type { Participation, Pot, User } from '@/lib/types'

// ─────────────────────────────────────────────────────────────
// 시간 헬퍼: 현재 시각 기준 상대 ISO 문자열 생성 (상대 표기가 항상 자연스럽게 보이도록)
// ─────────────────────────────────────────────────────────────
const now = Date.now()
const mins = (m: number) => new Date(now + m * 60_000).toISOString()
const hours = (h: number) => new Date(now + h * 60 * 60_000).toISOString()

// ─────────────────────────────────────────────────────────────
// 현재 로그인 사용자 (목업)
// ─────────────────────────────────────────────────────────────
export const CURRENT_USER_ID = 'u1'

export const USERS: User[] = [
  { id: 'u1', loginId: 'mukmate', nickname: '배고픈북극곰', zoneCode: 'DORM' },
  { id: 'u2', loginId: 'jinjin', nickname: '진수성찬', zoneCode: 'DORM' },
  { id: 'u3', loginId: 'yumyum', nickname: '냠냠박사', zoneCode: 'GUJEONGMUN' },
  { id: 'u4', loginId: 'latenight', nickname: '야식요정', zoneCode: 'SINJEONGMUN' },
  { id: 'u5', loginId: 'chickenlover', nickname: '치킨은진리', zoneCode: 'DORM' },
  { id: 'u6', loginId: 'malatang', nickname: '마라마라해', zoneCode: 'SADAEBUGO' },
]

// ─────────────────────────────────────────────────────────────
// 공동주문(Pot) — 8개 이상, 상태 섞음
// ─────────────────────────────────────────────────────────────
export const POTS: Pot[] = [
  {
    id: 'p1',
    hostId: 'u2',
    hostNickname: '진수성찬',
    zoneCode: 'DORM',
    storeName: '깐부치킨 전북대점',
    storeAddress: '전주시 덕진구 백제대로 567',
    orderSummary: '후라이드 + 양념 반반, 콜라 1.25L',
    targetType: 'HEADCOUNT',
    targetValue: 4,
    currentCount: 2,
    deliveryFee: 4000,
    deadlineAt: mins(23),
    pickupAt: hours(1),
    pickupName: '진수관 1층 로비',
    pickupAddress: '전북대학교 진수관',
    pickupNote: '로비 택배함 앞에서 만나요',
    extraNote: '기숙사생 우선이요! 뼈 없는 걸로 통일할게요.',
    status: 'OPEN',
    isLocationVerified: true,
    distanceMeters: 120,
    createdAt: mins(-40),
  },
  {
    id: 'p2',
    hostId: 'u3',
    hostNickname: '냠냠박사',
    zoneCode: 'GUJEONGMUN',
    storeName: '이삭토스트 구정문점',
    storeAddress: '전주시 덕진구 명륜3길 12',
    orderSummary: '햄치즈 토스트 여러 개, 최소주문 맞추기',
    targetType: 'AMOUNT',
    targetValue: 15000,
    currentCount: 3,
    currentAmount: 12000,
    deliveryFee: 3000,
    deadlineAt: mins(48),
    pickupAt: hours(1.5),
    pickupName: '구정문 앞 GS25',
    pickupAddress: '전주시 덕진구 백제대로 앞',
    pickupNote: '편의점 앞 벤치에서 나눠요',
    extraNote: '',
    status: 'OPEN',
    isLocationVerified: false,
    distanceMeters: 320,
    createdAt: mins(-25),
  },
  {
    id: 'p3',
    hostId: 'u6',
    hostNickname: '마라마라해',
    zoneCode: 'SADAEBUGO',
    storeName: '탕화쿵푸 마라탕',
    storeAddress: '전주시 덕진구 기린대로 21',
    orderSummary: '마라탕 + 꿔바로우, 4인 배달비 나누기',
    targetType: 'HEADCOUNT',
    targetValue: 4,
    currentCount: 3,
    deliveryFee: 5000,
    deadlineAt: mins(12),
    pickupAt: hours(0.8),
    pickupName: '사대부고 정문',
    pickupAddress: '전주시 덕진구 사대부고 앞',
    pickupNote: '정문 버스정류장 근처',
    extraNote: '맵기 중간으로 맞출게요',
    status: 'OPEN',
    isLocationVerified: true,
    distanceMeters: 640,
    createdAt: mins(-55),
  },
  {
    id: 'p4',
    hostId: 'u4',
    hostNickname: '야식요정',
    zoneCode: 'SINJEONGMUN',
    storeName: '피자스쿨 신정문점',
    storeAddress: '전주시 덕진구 소양로 88',
    orderSummary: '콤비네이션 L + 페퍼로니 L, 콜라',
    targetType: 'HEADCOUNT',
    targetValue: 3,
    currentCount: 1,
    deliveryFee: 3500,
    deadlineAt: mins(75),
    pickupAt: hours(2),
    pickupName: '참빛관 로비',
    pickupAddress: '전북대학교 참빛관',
    pickupNote: '엘리베이터 앞에서 만나요',
    extraNote: '',
    status: 'OPEN',
    isLocationVerified: false,
    distanceMeters: 480,
    createdAt: mins(-15),
  },
  {
    id: 'p5',
    hostId: 'u5',
    hostNickname: '치킨은진리',
    zoneCode: 'DORM',
    storeName: '엽기떡볶이 전북대점',
    storeAddress: '전주시 덕진구 백제대로 601',
    orderSummary: '엽떡 착한맛 + 오뎅 + 주먹밥 세트',
    targetType: 'AMOUNT',
    targetValue: 20000,
    currentCount: 4,
    currentAmount: 20000,
    deliveryFee: 3000,
    deadlineAt: mins(-30),
    pickupAt: mins(20),
    pickupName: '학군단 앞',
    pickupAddress: '전북대학교 학군단',
    pickupNote: '',
    extraNote: '마감했어요~ 곧 픽업입니다',
    status: 'CLOSED',
    isLocationVerified: true,
    distanceMeters: 210,
    createdAt: hours(-2),
  },
  {
    id: 'p6',
    hostId: 'u3',
    hostNickname: '냠냠박사',
    zoneCode: 'GUJEONGMUN',
    storeName: '봉구스밥버거 구정문',
    storeAddress: '전주시 덕진구 명륜3길 30',
    orderSummary: '밥버거 여러 종류 + 라볶이',
    targetType: 'HEADCOUNT',
    targetValue: 5,
    currentCount: 5,
    deliveryFee: 2500,
    deadlineAt: hours(-3),
    pickupAt: hours(-2),
    pickupName: '구정문 편의점 앞',
    pickupAddress: '전주시 덕진구 백제대로 앞',
    pickupNote: '',
    extraNote: '',
    status: 'ORDERED',
    isLocationVerified: false,
    distanceMeters: 350,
    createdAt: hours(-5),
  },
  {
    id: 'p7',
    hostId: 'u1',
    hostNickname: '배고픈북극곰',
    zoneCode: 'DORM',
    storeName: '스시로우 전주점',
    storeAddress: '전주시 덕진구 백제대로 700',
    orderSummary: '초밥 세트 2개, 최소주문 + 배달비 나눔',
    targetType: 'AMOUNT',
    targetValue: 30000,
    currentCount: 2,
    currentAmount: 18000,
    deliveryFee: 4500,
    deadlineAt: mins(95),
    pickupAt: hours(2.5),
    pickupName: '진수관 1층 로비',
    pickupAddress: '전북대학교 진수관',
    pickupNote: '로비 소파쪽',
    extraNote: '연어 좋아하시는 분 환영',
    status: 'OPEN',
    isLocationVerified: true,
    distanceMeters: 130,
    createdAt: mins(-8),
  },
  {
    id: 'p8',
    hostId: 'u4',
    hostNickname: '야식요정',
    zoneCode: 'SINJEONGMUN',
    storeName: '맘스터치 신정문점',
    storeAddress: '전주시 덕진구 소양로 60',
    orderSummary: '싸이버거 세트 + 치즈스틱, 배달비 3천',
    targetType: 'HEADCOUNT',
    targetValue: 4,
    currentCount: 3,
    deliveryFee: 3000,
    deadlineAt: mins(38),
    pickupAt: hours(1.2),
    pickupName: '신정문 버스정류장',
    pickupAddress: '전주시 덕진구 신정문 앞',
    pickupNote: '정류장 벤치',
    extraNote: '',
    status: 'OPEN',
    isLocationVerified: false,
    distanceMeters: 520,
    createdAt: mins(-18),
  },
  {
    id: 'p9',
    hostId: 'u2',
    hostNickname: '진수성찬',
    zoneCode: 'DORM',
    storeName: '역전할머니맥주 안주 배달',
    storeAddress: '전주시 덕진구 백제대로 620',
    orderSummary: '노가리 + 감자튀김, 야식 공동주문',
    targetType: 'HEADCOUNT',
    targetValue: 3,
    currentCount: 3,
    deliveryFee: 3000,
    deadlineAt: hours(-1),
    pickupAt: mins(-30),
    pickupName: '진수관 로비',
    pickupAddress: '전북대학교 진수관',
    pickupNote: '',
    extraNote: '취소되었습니다 (가게 마감)',
    status: 'CANCELED',
    isLocationVerified: false,
    distanceMeters: 140,
    createdAt: hours(-4),
  },
]

// ─────────────────────────────────────────────────────────────
// 참여 신청(Participation)
// ─────────────────────────────────────────────────────────────
export const PARTICIPATIONS: Participation[] = [
  {
    id: 'pa1',
    potId: 'p1',
    userId: 'u3',
    nickname: '냠냠박사',
    applyMessage: '양념 반반 좋아요! 뼈없는거 저도 찬성입니다.',
    menuAmount: 9000,
    approvalStatus: 'APPROVED',
    createdAt: mins(-30),
  },
  {
    id: 'pa2',
    potId: 'p1',
    userId: 'u5',
    nickname: '치킨은진리',
    applyMessage: '치킨은 언제나 옳죠 참여할게요~',
    menuAmount: 9000,
    approvalStatus: 'PENDING',
    createdAt: mins(-12),
  },
  {
    id: 'pa3',
    potId: 'p1',
    userId: 'u4',
    nickname: '야식요정',
    applyMessage: '콜라 제가 넉넉히 시킬게요',
    menuAmount: 10000,
    approvalStatus: 'PENDING',
    createdAt: mins(-6),
  },
  {
    id: 'pa4',
    potId: 'p1',
    userId: 'u6',
    nickname: '마라마라해',
    applyMessage: '자리 남았나요?',
    menuAmount: 8000,
    approvalStatus: 'REJECTED',
    createdAt: mins(-20),
  },
  {
    id: 'pa5',
    potId: 'p7',
    userId: 'u3',
    nickname: '냠냠박사',
    applyMessage: '연어초밥 완전 좋아요',
    menuAmount: 12000,
    approvalStatus: 'APPROVED',
    createdAt: mins(-5),
  },
  {
    id: 'pa6',
    potId: 'p7',
    userId: 'u5',
    nickname: '치킨은진리',
    applyMessage: '초밥 참여요!',
    menuAmount: 11000,
    approvalStatus: 'PENDING',
    createdAt: mins(-3),
  },
]

// 채팅방/메시지는 Phase 4부터 실제 DB(chat_rooms/messages)를 쓴다 — 여기 있던
// CHAT_ROOMS/MESSAGES mock은 제거함. 커뮤니티 고정방 2개는 scripts/seed.ts로 시드한다.

// 장소 검색은 Phase 3부터 카카오 로컬 API를 실시간으로 호출한다 (app/api/places/search) —
// 목 데이터로 흉내낼 필요가 없어져서 여기 있던 PLACES/FREQUENT_PICKUP_PLACES/RECENT_PLACE_KEYWORDS는 제거함.
